// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDijh_5yVX4bJSG_QI8sDTqH4uINq6yt2Y',
    appId: '1:481131505194:web:a6927e28e932d11648c553',
    messagingSenderId: '481131505194',
    projectId: 'tryb-ludo-v1',
    authDomain: 'tryb-ludo-v1.firebaseapp.com',
    storageBucket: 'tryb-ludo-v1.firebasestorage.app',
    measurementId: 'G-DX930DLSVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiGdeLVKH_Jz_YYR036bcA7WwXnspxQmk',
    appId: '1:481131505194:android:681b9302127ab0f848c553',
    messagingSenderId: '481131505194',
    projectId: 'tryb-ludo-v1',
    storageBucket: 'tryb-ludo-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaOhDIBz8UwVFf0NmGN-UhNv8nFmSUnyc',
    appId: '1:481131505194:ios:81c1cc2590263e9648c553',
    messagingSenderId: '481131505194',
    projectId: 'tryb-ludo-v1',
    storageBucket: 'tryb-ludo-v1.firebasestorage.app',
    iosBundleId: 'com.example.trybLudoV1',
  );

}